import asyncio
from pathlib import Path

from backend.core.config import app_config

_README_SPLATFORGE = """\
# SplatForge Scene — README
==============================

This export was generated by the 3DGS Pipeline App using the SplatForge Blender add-on.

## Contents
  scene.blend  — Blender scene with the 3D Gaussian Splatting object imported via SplatForge.

## How to use
1. Install Blender 4.x (https://www.blender.org/download/)
2. Install the SplatForge add-on from the Blender add-on market or from source.
3. Open scene.blend in Blender.
4. The Gaussian splat object is ready to render or export.

## Re-importing manually
If you want to re-import the PLY directly:
  Edit > Preferences > Add-ons > Install → select SplatForge
  File > Import > 3D Gaussian Splat (.ply)

## Notes
  - scene.blend is linked to point_cloud.ply in ../lfs_output/ — keep the folder structure intact.
  - For WebGL viewer export, use SuperSplat: {supersplat_url}
"""


async def run_blender_real(project_path: Path, broadcast_fn, settings: dict) -> dict:
    """Calls Blender headless with the splatforge import script."""
    blender_exe = app_config.tools.blender_exe_path
    if not blender_exe:
        raise FileNotFoundError(
            "blender_exe_path is not configured.\n"
            "Enable blender_stub in Settings or set blender_exe_path."
        )

    export_dir = project_path / "export"
    ply_files = list(export_dir.glob("*.ply"))
    if not ply_files:
        raise FileNotFoundError(f"No .ply file found in {export_dir}")

    ply = ply_files[0]
    out_blend = export_dir / "scene.blend"
    script = Path(__file__).parents[2] / "scripts" / "blender_splatforge.py"

    cmd = [
        blender_exe,
        "--background",
        "--python", str(script),
        "--", "--ply", str(ply), "--out", str(out_blend),
    ]
    await broadcast_fn("blender", "INFO", f"[Blender] Running: {' '.join(cmd)}")

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )

    try:
        async for raw in proc.stdout:
            line = raw.decode("utf-8", errors="replace").strip()
            await broadcast_fn("blender", "INFO", line)

        await asyncio.wait_for(proc.wait(), timeout=1800)
    except asyncio.TimeoutError:
        proc.kill()
        raise RuntimeError("Blender timed out after 30 minutes")
    except asyncio.CancelledError:
        # An aborted step must not leave Blender running headless.
        if proc.returncode is None:
            proc.kill()
        raise

    if proc.returncode != 0:
        raise RuntimeError(f"Blender exited with code {proc.returncode}")

    readme = _README_SPLATFORGE.format(supersplat_url=app_config.tools.supersplat_url)
    (export_dir / "README_SPLATFORGE.txt").write_text(readme, encoding="utf-8")

    await broadcast_fn(
        "blender", "SUCCESS",
        f"[Blender] Scene exported → {out_blend}",
        progress=1.0,
    )
    return {"blend_path": str(out_blend)}


async def run_blender_stub(project_path: Path, broadcast_fn, settings: dict) -> dict:
    """Simulates Blender SplatForge export with 3 phases over 5 seconds."""
    export_dir = project_path / "export"
    export_dir.mkdir(exist_ok=True)

    phases = [
        (0.2, "Loading scene..."),
        (0.6, "Importing PLY..."),
        (0.9, "Configuring SplatForge..."),
    ]
    phase_sleep = 5.0 / len(phases)

    await broadcast_fn(
        "blender", "INFO",
        "[STUB] Blender stub active — simulating SplatForge scene export",
        progress=0.0,
    )

    for prog, phase in phases:
        await asyncio.sleep(phase_sleep)
        await broadcast_fn("blender", "INFO", f"[STUB] {phase}", progress=prog)

    blend_path = export_dir / "scene.blend"
    blend_path.write_text(
        "# STUB scene.blend — generated by 3dgs-pipeline-app stub mode\n"
        "# Replace with a real Blender export when Blender is available.\n",
        encoding="utf-8",
    )

    readme = _README_SPLATFORGE.format(supersplat_url=app_config.tools.supersplat_url)
    (export_dir / "README_SPLATFORGE.txt").write_text(readme, encoding="utf-8")

    await broadcast_fn(
        "blender", "SUCCESS",
        f"[STUB] Blender complete → {blend_path}",
        progress=1.0,
    )
    return {"blend_path": str(blend_path)}


async def run_blender(project_path: Path, broadcast_fn, settings: dict) -> dict:
    if app_config.stubs.blender_stub:
        return await run_blender_stub(project_path, broadcast_fn, settings)
    return await run_blender_real(project_path, broadcast_fn, settings)
