"""
Generates a minimal valid 3D Gaussian Splatting .ply file for stub testing.
Run once: python tools/test_assets/generate_sample_ply.py
"""
import shutil
import struct
import random
import math
from pathlib import Path

OUTPUT = Path(__file__).parent / "sample.ply"
N = 500  # number of Gaussians

def write_ply_header(f, n):
    header = f"""ply
format binary_little_endian 1.0
comment 3DGS stub sample - generated by 3dgs-pipeline-app
element vertex {n}
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header\n"""
    f.write(header.encode("ascii"))

def write_ply_data(f, n):
    for i in range(n):
        # Random position in a 2m sphere
        theta = random.uniform(0, 2 * math.pi)
        phi = math.acos(random.uniform(-1, 1))
        r = random.uniform(0, 1.0)
        x = r * math.sin(phi) * math.cos(theta)
        y = r * math.sin(phi) * math.sin(theta)
        z = r * math.cos(phi)
        # Normal (unit, random)
        nx, ny, nz = 0.0, 0.0, 1.0
        # SH DC (color ~warm grey)
        f_dc_0 = random.uniform(0.3, 0.8)
        f_dc_1 = random.uniform(0.3, 0.7)
        f_dc_2 = random.uniform(0.2, 0.6)
        # SH rest (zeroed)
        f_rest = [0.0, 0.0, 0.0]
        # Opacity (logit ~0.8)
        opacity = 1.386  # sigmoid(1.386) ≈ 0.8
        # Scale (log scale, small ellipsoids)
        scale = [random.uniform(-4.0, -2.5)] * 3
        # Rotation quaternion (identity-ish)
        rot = [1.0, 0.0, 0.0, 0.0]

        values = [x, y, z, nx, ny, nz, f_dc_0, f_dc_1, f_dc_2,
                  *f_rest, opacity, *scale, *rot]
        f.write(struct.pack(f"{len(values)}f", *values))

with open(OUTPUT, "wb") as f:
    write_ply_header(f, N)
    write_ply_data(f, N)

print(f"[stub] Generated {N} Gaussians → {OUTPUT}")
print(f"[stub] File size: {OUTPUT.stat().st_size / 1024:.1f} KB")

STUB_COPY = OUTPUT.parent / "stub_pointcloud.ply"
shutil.copy2(OUTPUT, STUB_COPY)
print(f"[stub] Copied → {STUB_COPY}")
